import type { Metadata } from 'next';
import {
  Geist,
  Geist_Mono,
  Inter,
  Crimson_Pro,
  Manrope,
  DM_Sans,
  DM_Serif_Text,
} from 'next/font/google';
import './globals.css';
import NavBar from '@/archive/NavBar';
import SideNavBar from '@/components/SideNavBar';

const dmSans = DM_Sans({
  variable: '--font-dm-sans',
  subsets: ['latin'],
});

const dmSerifText = DM_Serif_Text({
  weight: '400',
  variable: '--font-dm-serif-text',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: {
    icon: '/app/flourish_green_flower.svg',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`flex flex-row ${dmSans.variable} ${dmSerifText.variable} antialiased`}
      >
        <SideNavBar />
        <div className="flex-1 ml-55">{children}</div>
      </body>
    </html>
  );
}
